version: '2.1'

services:
  application-boilerplate:
    image: application-boilerplate
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3005:3005
      - 9229:9229
    ## set your startup file here
    command: node --inspect=0.0.0.0:9229 index.js